app:
  name: tradeverse
  env: development
  secret: supersecretkey123

admin:
  user_id: 1
  email: admin@gmail.com
  password: admin
  # commission: 10

server:
  admin_port: 8080
  customer_port: 8081
  trader_port: 8082

cookie:
  domain: localhost 

database:
  host: localhost
  port: 5432
  user: postgres
  password: "@postgres"
  name: tradeverse
  sslmode: disable

jwt:
  secret: supersecretjwtkey
  expire_hours: 24

redis:
  host: localhost
  port: 6379
